// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./components/Board.vue')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    MdiHandshakeOutline: typeof import('~icons/mdi/handshake-outline')['default']
    TgBoard: typeof import('./components/TgBoard.vue')['default']
    TgSquare: typeof import('./components/TgSquare.vue')['default']
    'TgSquare copy': typeof import('./components/TgSquare copy.vue')['default']
    TgTimer: typeof import('./components/TgTimer.vue')['default']
  }
}

export { }
