// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./components/Board.vue')['default']
    'Board copy': typeof import('./components/Board copy.vue')['default']
    BoardSelf: typeof import('./components/Board-self.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    'Footer copy': typeof import('./components/Footer copy.vue')['default']
    Game: typeof import('./components/game.vue')['default']
    MdiHandshakeOutline: typeof import('~icons/mdi/handshake-outline')['default']
    README: typeof import('./components/README.md')['default']
    Square: typeof import('./components/Square.vue')['default']
    'Square copy': typeof import('./components/Square copy.vue')['default']
    TgBoard: typeof import('./components/TgBoard.vue')['default']
    TgSquare: typeof import('./components/TgSquare.vue')['default']
    TicTacToeGame: typeof import('./components/tic-tac-toe-game.vue')['default']
  }
}

export { }
